### ISSUE TITLE
dependencies update

### ISSUE THREAD

**Issue by BenOnTrack** [FunMiles/Planetiler_MapLibre_Sveltekit#1]
Hi Michel,
I've tried to install and run your application but it seems there's an issue with some dependencies. Anyway you could have a look ?
Regards,
Ben

**Comment by FunMiles** [comment]
Ben,

I suspect it may be due to the recent changes to Svelte/Sveltekit. I will take a look and try to address it but it may take me a week or two before I can do it. If you are able to get it to work before, please submit a PR with your fixes.

Michel

PS: It seems to be the server-side sqlite3 C++ code compilation that breaks. The version used relies on the v8 javascript node.js engine internals and they have changed.
PPS: Updating the better-squlite3 allows to finish the `pnpm i` but `pnpm dev` fails, and now it seems to be related to the sveltekit upgrade.

**Comment by FunMiles** [comment]
@BenOnTrack The latest update should address both the sqlite3 and the new Svelte/Sveltekit issues. Give it a try and let us know if you have any more problems.

**Comment by BenOnTrack** [comment]
Hi @FunMiles , that works great! Thanks a lot. 
I'm curious to see what's best between your embedded solution versus implementing tileserver-gl ?

**Comment by FunMiles** [comment]
@BenOnTrack Glad to hear. I'll close the issue. Thanks for reporting it, it got me to do a few more things that I will be using soon in another project of mine.
To give a partial answer to your question from my point of view and limited knowledge of tileserver-gl:
   - tileserver-gl can do server-side rendering and serve bitmaps. The embedded approach cannot. It might be possible to add it, but it is not the goal here.
   - The embedded approach is quite light weight on the server and you do not need to run a separate API server and all the associated cross-origin authorization complexity if you don't want everybody to use your API from their own apps. It should also be fairly easy to replace sqlite3 on the server with a cloud database so that it can run on cloudflare or vercel for example. This is one thing I will be doing for my project.
Le me know if you end up using this approach in a project, public or otherwise, I'd love to hear about it/see it in action.

**Comment by BenOnTrack** [comment]
Thanks! I'm completely new to svelte (and coding in general) and I'm just trying to put a MVP with capacitor using your approach. I haven't succeeded at the moment (as I've only found how to run a static app with capacitor while this wouldn't be static at all) and I'll keep you posted if I ever manage to go further. Thanks in any case, really appreciate the support and it'll help me assess what's best between your embedded solution versus sth like tileserver-gl

What would be interested is to know how you're planning to handle multiple mbtiles at once, since at the moment the GET function fetches the unique Planet.mbtiles, but that's another story
