### ISSUE TITLE
Serve local sprites and glyphs

### ISSUE THREAD

**Issue by BenOnTrack** [FunMiles/Planetiler_MapLibre_Sveltekit#2]
hi @FunMiles 
if you replace your glyphs input with `"glyphs": "glyphs/{fontstack}/{range}.pbf",` and store your local glyphs under `static` then you can serve local glyphs.

I'm trying to do something similar for the sprite, but unsuccessful at the moment
`"sprite": "@origin@/sprites/sprite",`
with a folder sprites under `routes` that contain a `sprite.json` (+png)

Any idea ? 
FYI you can create your own sprite using https://github.com/mapbox/spritezero

**Comment by FunMiles** [comment]
@BenOnTrack I have enabled the discussion feature on this repository. 
I am not sure about the sprites, but as a quick comment, if you have json and png data, they should probably be under `static`. The `routes` directory should contain code, either `.svelte` for pages or `.js`/`.ts` for endpoints. If you want to generate sprites json and png files on the fly, then you would put some `.png.js` files for the generating endpoint. Otherwise, if they have been generated as static assets once and for all, then put them in the `static` directory.
